### ISSUE TITLE
KB Article: Native Contract Events

### ISSUE THREAD

**Issue by melpadden** [casper-network/condor-info#37]
### Discussed in https://github.com/casper-network/condor-info/discussions/21

<div type='discussions-op-text'>

<sup>Originally posted by **sczembor** June 26, 2024</sup>
What are and how do Contract-Level Events relate to CES events and the events found in CEP-47? </div>

**Comment by Adrian-Wrona** [comment]
@melpadden and @asladeofgreen to review this
