### ISSUE TITLE
[Condor-Release]: Cannot install contract with an EntryPointType::Caller

### ISSUE THREAD

**Issue by davidatwhiletrue** [casper-network/condor-info#87]
### Category

Request for Tech Support

### Project Name(Optional)

MAKE

### Casper Network

Devnet

### Priority

Medium

### Node Functionality

Execution Engine

### Description

Trying to install a contract containing one entry point with type `EntryPointType::Caller`.
The installation fails in `add_contract_version()` with `InvalidEntryPointType`.

Should this type of entry point work in Condor?

### Date Issue Began(optional)

25/07/2024

**Comment by cspramit** [comment]
From Karan - No we disable entry point sessions in 2.0
We don’t allow new contracts with those entry points to be installed
